version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch
    resource_class: 2xlarge
    steps:
      - checkout
      - run: sudo pip install s3cmd
      - run:
          name: Build & upload sysroots
          command: ./build/linux/sysroot_scripts/build_and_upload.py
          no_output_timeout: 30m
      - store_artifacts:
          path: build/linux/sysroot_scripts/sysroots.json
          destination: sysroots.json
